import { 
  Book, 
  Scale, 
  Handshake, 
  Users, 
  Leaf, 
  Wind, 
  Droplets, 
  Zap, 
  Briefcase, 
  Factory, 
  Globe, 
  Heart, 
  ShieldCheck, 
  Target, 
  MessageSquare,
  Sprout
} from 'lucide-react';

export const SDGs = [
  {
    id: 1,
    number: "1",
    name: "No Poverty",
    color: "bg-[#E5243B]",
    hex: "#E5243B",
    textColor: "text-white",
    icon: Heart,
  },
  {
    id: 2,
    number: "2",
    name: "Zero Hunger",
    color: "bg-[#DDA63A]",
    hex: "#DDA63A",
    textColor: "text-white",
    icon: Sprout,
  },
  {
    id: 3,
    number: "3",
    name: "Good Health and Well-being",
    color: "bg-[#4C9F38]",
    hex: "#4C9F38",
    textColor: "text-white",
    icon: Heart,
  },
  {
    id: 4,
    number: "4",
    name: "Quality Education",
    color: "bg-[#C5192D]",
    hex: "#C5192D",
    textColor: "text-white",
    icon: Book,
  },
  {
    id: 5,
    number: "5",
    name: "Gender Equality",
    color: "bg-[#FF3A21]",
    hex: "#FF3A21",
    textColor: "text-white",
    icon: Users,
  },
  {
    id: 6,
    number: "6",
    name: "Clean Water and Sanitation",
    color: "bg-[#26BDE2]",
    hex: "#26BDE2",
    textColor: "text-white",
    icon: Droplets,
  },
  {
    id: 7,
    number: "7",
    name: "Affordable and Clean Energy",
    color: "bg-[#FCC30B]",
    hex: "#FCC30B",
    textColor: "text-black",
    icon: Zap,
  },
  {
    id: 8,
    number: "8",
    name: "Decent Work and Economic Growth",
    color: "bg-[#A21942]",
    hex: "#A21942",
    textColor: "text-white",
    icon: Briefcase,
  },
  {
    id: 9,
    number: "9",
    name: "Industry, Innovation and Infrastructure",
    color: "bg-[#FD6925]",
    hex: "#FD6925",
    textColor: "text-white",
    icon: Factory,
  },
  {
    id: 10,
    number: "10",
    name: "Reduced Inequality",
    color: "bg-[#DD1367]",
    hex: "#DD1367",
    textColor: "text-white",
    icon: Users,
  },
  {
    id: 11,
    number: "11",
    name: "Sustainable Cities and Communities",
    color: "bg-[#FD9D24]",
    hex: "#FD9D24",
    textColor: "text-white",
    icon: Globe,
  },
  {
    id: 12,
    number: "12",
    name: "Responsible Consumption and Production",
    color: "bg-[#BF8B2E]",
    hex: "#BF8B2E",
    textColor: "text-white",
    icon: Leaf,
  },
  {
    id: 13,
    number: "13",
    name: "Climate Action",
    color: "bg-[#3F7E44]",
    hex: "#3F7E44",
    textColor: "text-white",
    icon: Wind,
  },
  {
    id: 14,
    number: "14",
    name: "Life Below Water",
    color: "bg-[#0A97D9]",
    hex: "#0A97D9",
    textColor: "text-white",
    icon: Droplets,
  },
  {
    id: 15,
    number: "15",
    name: "Life on Land",
    color: "bg-[#56C02B]",
    hex: "#56C02B",
    textColor: "text-white",
    icon: Sprout,
  },
  {
    id: 16,
    number: "16",
    name: "Peace, Justice and Strong Institutions",
    color: "bg-[#00689D]",
    hex: "#00689D",
    textColor: "text-white",
    icon: Scale,
  },
  {
    id: 17,
    number: "17",
    name: "Partnerships for the Goals",
    color: "bg-[#19486A]",
    hex: "#19486A",
    textColor: "text-white",
    icon: Handshake,
  },
];

export const getSDGById = (id) => {
  if (!id) return null;
  const searchId = id.toString().trim();
  return SDGs.find((sdg) => 
    sdg.number === searchId || 
    sdg.id.toString() === searchId
  );
};

export const CORE_SDGS = ["4", "16", "17"];
